spring:
  jpa:
    show-sql: true
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
  #        generate_statistics: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: hillel2020
    driverClassName: org.postgresql.Driver
  jackson:
    default-property-inclusion: non_null
jwt:
  secret: some_secret

client:
  someapi:
    url: https://jsonplaceholder.typicode.com/
